#!/usr/bin/env bash
# Update package index

apt-get update


apt-get install -y nginx


sed -i 's/^\(listen\s\+\)80\(\s*;\)/\180\2/' /etc/nginx/sites-available/default

service nginx restart


echo "Holberton School" > /var/www/html/index.html
