#!/usr/bin/env bash
# Update package index

apt-get update


apt-get install -y nginx


sed -i 's/^\(listen\s\+\)80\(\s*;\)/\180\2/' /etc/nginx/sites-available/default

service nginx restart


echo "<html><head><title>Hello World!</title></head><body><h1>Hello World!</h1></body></html>" > /var/www/html/index.html
