#!/usr/bin/env bash
#task
sudo apt-get update
sudo apt-get install -y nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\asma100 permanent;"
sudo sed -i "s/server_name; /$replacement/" /etc/nginx/sites-enabled/default
sudo service nginx restart