#!/usr/bin/env bash
#task 0
sudo apt-get update -y
sudo apt-get install nginx -y
echo "Hello World!" | sudo dd status=none of=/var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html 
r="\\\n\tlocation /redirect_me {\n\t\t return 301 https://github.com/asma100;\n\t}\n"
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.backup
sudo sed -i "53i $r" /etc/nginx/sites-available/default
r="\\\n\terror_page 404 /404.html;\n\n\tlocation = /404.html {\n\t\tinternal;\n\t}\n"
sudo sed -i "53i $r" /etc/nginx/sites-available/default
sudo sed -i "/server_name _/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default
sudo nginx -t
sudo service nginx reload