#!/usr/bin/env bash
# Update and Upgrade System
sudo apt update && sudo apt upgrade -y

# Install HAproxy
sudo apt install haproxy -y

# Configure HAproxy for Load Balancing


# Create HAproxy configuration file
server_config=\
"
frontend  besthor_frontend
        bind *:80
        mode http
        default_backend besthor_backend
backend besthor_backend
        balance roundrobin
        server 497141-web-01 54.236.53.167:80 check
        server 497141-web-02 54.236.26.139:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Testing the HAproxy configuration file
sudo haproxy -c -f /etc/haproxy/haproxy.cfg
