#!/usr/bin/env bash
#pid

echo "$$" > /var/run/myscript.pid

for (( ; ; )); do
echo "To infinity and beyond"
  sleep 2 
trap 'echo "Y U no love me?!"' SIGINT
trap 'echo "I hate the kill command"&& rm /var/run/myscript.pid' SIGTERM
trap 'rm /var/run/myscript.pid' SIGQUIT
done