#!/usr/bin/env bash
# This script is displaying clock
i=1

while ((i <= 12)); do
    echo "Hour: $i"
    
    j=0
    while ((j <= 59)); do
        echo "$j"
        ((j++))
    done
    
    ((i++))
done